package org.rs3emulator.server.network.channel

enum class ResultType(val id: Int) {
    FUTURE_CLOSE(-1),
    SUCCESS(0),
    LOGIN_SUCCESS(2),
    CREDENTIALS_INVALID(3),
    CREDENTIALS_BLACKLISTED_BAN(4),
    SESSION_ACTIVE(5),
    VERSION_OUTDATED(6),
    WORLD_CAPACITY(7),
    CONNECTION_FAILED_LOGINSERVER(8),
    SESSION_LIMIT(9),
    BAD_SESSION(10),
    CREDENTIALS_UNSECURE(11),
    CREDENTIALS_SUBSCRIPTION(12),
    WORLD_UPDATE(14),
    CREDENTIALS_FAILSAFE(16),
    PROFILE_LOCKED(18),
    PROFILE_BAD(24),
    CREDENTIALS_BLACKLISTED_MACBAN(26),
    CREDENTIALS_PROFANITY(31);
}